version: "1.0"
info:
  model: int-scaffold
packages:
- name: MmadplayProject
  gitServerName: mmadplay
  gitUrl: https://github.com/madhumadineni/MmadplayProject
  gitUsername: madhumadineni
  gitBranch: main
- name: ESBTest
  gitServerName: mmadplay
  gitUrl: https://github.com/madhumadineni
  gitUsername: madhumadineni
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
services:
- serviceName: project.mmadplay.integrations:GetDate
  packages:
  - name: MmadplayProject
    version: "1.0"
  - name: ESBTest
    version: "1.0"
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: ESBTest.services:testflow
  packages:
  - name: ESBTest
    version: "1.0"
- serviceName: pub.json:jsonStringToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.date:getCurrentDateString
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: KBLog4j2.javaservices:logIData
  packages:
  - name: MmadplayProject
    version: "1.0"
  - name: ESBTest
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.mmadplay.integrations:testq
  packages:
  - name: MmadplayProject
    version: "1.0"
  - name: ESBTest
    version: "1.0"
- serviceName: project.mmadplay.integrations:date
  packages:
  - name: MmadplayProject
    version: "1.0"
  - name: ESBTest
    version: "1.0"
- serviceName: pub.date:dateTimeBuild
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_11
  packages:
  - name: MmadplayProject
    version: "1.0"
  - name: ESBTest
    version: "1.0"
configurationVariables:
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionManagerSettings.poolable
  : "false"
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionEnabled
  : "false"
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.password
  : "{AES}jSeiwgyC3vw29RmsdD7cFA=="
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.trustStore
  : ""
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.user
  : temp1
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.dbType
  : ORACLE
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.databaseName
  : ""
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.portNumber
  : "1521"
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.networkProtocol
  : tcp
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.serverName
  : temp
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.MmadplayProject.project.mmadplay.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11.connectionSettings.keyStore
  : ""
